---
title: "Infant gestures"
author: "Stefano Coretta"
date: "17/07/2018"
output: 
  pdf_document: 
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../"))
library(tidyverse)
theme_set(theme_minimal())
library(fitdistrplus)
```

# Read data

```{r read, message=FALSE}
gestures <- read_csv("./data/gestures.csv")

gestures_tot <- gestures %>%
  group_by(dyad, background, months, gesture) %>%
  summarise(
    count = sum(count),
    ct = sum(ct)
  ) %>%
  ungroup() %>%
  mutate(
    gesture = factor(gesture, levels = c("reach", "point", "ho_gv"))
  ) %>%
  mutate_if(is.character, as.factor)

utterances <- read_csv("./data/utterances.csv")

# NAs not removed in sum()
utterances_tot <- utterances %>%
  group_by(dyad, background, months) %>%
  summarise(
    utterances = sum(utterances)
  ) %>%
  ungroup() %>%
  mutate_if(is.character, as.factor)

point <- gestures %>%
  filter(gesture == "point") %>%
  group_by(dyad, background, months) %>%
  summarise(
    count = sum(count)
  ) %>%
  ungroup() %>%
  mutate_if(is.character, as.factor)

utter_point <- left_join(utterances_tot, point) %>%
  rename(point = count)

utterances_compl <- utterances %>% na.omit()
utterances_tcompl <- utterances_tot %>% na.omit()
```

# Summaries

Number of dyads per background.

```{r n-dyads}
gestures %>% group_by(background) %>% summarise(n = n_distinct(dyad))
```

```{r n-dyads}
utterances %>% group_by(background) %>% summarise(n = n_distinct(dyad))
```

20 Bangladeshi, 20 Chinese, 19 English.

`gestures` has 21 missing values. `utterances` has 12 missing values.

# Plot data

## Gestures

```{r density}
gestures_tot %>%
  ggplot(aes(count)) +
  geom_density() +
  geom_rug() +
  geom_vline(xintercept = median(gestures_tot$count, na.rm = TRUE), linetype = "dashed", colour = "orange") +
  geom_vline(xintercept = mean(gestures_tot$count, na.rm = TRUE), linetype = "dotted", colour = "blue")
```

```{r density-31}
gestures_tot %>%
  filter(count < 31) %>%
  ggplot(aes(count)) +
  geom_density() +
  geom_rug() +
  geom_vline(xintercept = median(gestures_tot$count, na.rm = TRUE), linetype = "dashed", colour = "orange") +
  geom_vline(xintercept = mean(gestures_tot$count, na.rm = TRUE), linetype = "dotted", colour = "blue")
```

```{r descdist}
gest_na <- na.omit(gestures_tot)
descdist(gest_na$count, discrete = TRUE)
```

```{r pois-plot}
plot(fitdist(gest_na$count, "pois"))
```

```{r nbinom-plot}
plot(fitdist(gest_na$count, "nbinom"))
```

```{r density-months-gest}
gestures_tot %>%
  ggplot(aes(count, fill = as.factor(months))) +
  geom_density(alpha = 0.5) +
  facet_grid(~ gesture)
```

## Utterances

```{r utter-density}
utterances %>%
  ggplot(aes(utterances)) +
  geom_density() +
  geom_rug()
```

```{r utter-tot-density}
utterances_tot %>%
  ggplot(aes(utterances)) +
  geom_density() +
  geom_rug()
```

```{r utter-tot-distr}
descdist(utterances_tcompl$utterances, discrete = TRUE)
```


```{r norm-plot}
plot(fitdist(utterances_tcompl$utterances, "norm"))
```

```{r utter-background}
utterances_tot %>%
  ggplot(aes(utterances, fill = background)) +
  geom_density(alpha = 0.5, colour = NA) +
  geom_rug()
```

```{r utter-months}
utterances_tot %>%
  ggplot(aes(utterances, fill = as.factor(months))) +
  geom_density(alpha = 0.5, colour = NA) +
  geom_rug()
```

```{r utter-months-jitter}
utterances_tot %>%
  ggplot(aes(as.factor(months), utterances)) +
  geom_jitter(width = 0.1)
```

```{r utter-months-jitter}
utterances_tot %>%
  ggplot(aes(as.factor(months), utterances, colour = background)) +
  geom_jitter(width = 0.1) +
  facet_grid(~ background)
```

```{r utter-months-line}
utterances_tot %>%
  group_by(background, months) %>%
  summarise(mean = mean(utterances, na.rm = TRUE)) %>%
  ggplot(aes(as.factor(months), mean, group = background, colour = background)) +
  geom_point() +
  geom_line() +
  ylim(c(min(utterances_tot$utterances, na.rm = TRUE), max(utterances_tot$utterances, na.rm = TRUE)))
```

```{r utter-months-line}
utterances_tot %>%
  group_by(background, months) %>%
  summarise(median = median(utterances, na.rm = TRUE)) %>%
  ggplot(aes(as.factor(months), median, group = background, colour = background)) +
  geom_point() +
  geom_line() +
  ylim(c(min(utterances_tot$utterances, na.rm = TRUE), max(utterances_tot$utterances, na.rm = TRUE)))
```

```{r utter-months-jitter}
utterances %>%
  ggplot(aes(as.factor(months), utterances, colour = task)) +
  geom_jitter(width = 0.1) +
  facet_grid(~ task)
```



```{r utter-months-background-jitter}
utterances %>%
  ggplot(aes(as.factor(months), utterances, colour = task)) +
  geom_jitter(width = 0.1) +
  facet_grid(background ~ task)
```

```{r utter-months-background-jitter}
utterances %>%
  ggplot(aes(as.factor(months), utterances, colour = task, group = dyad)) +
  geom_point() +
  geom_line() +
  facet_grid(background ~ task)
```

```{r utter-months-background-jitter-2}
utterances_tot %>%
  ggplot(aes(as.factor(months), utterances, colour = background)) +
  geom_jitter(width = 0.1) +
  facet_grid(background ~ .)
```

```{r utter-months-background-line}
utterances_tot %>%
  ggplot(aes(as.factor(months), utterances, colour = background)) +
  # geom_boxplot(width = 0.5, aes(colour = NULL)) +
  geom_point() +
  geom_line(aes(group = dyad)) +
  facet_grid(background ~ .)
```

```{r utter-background-jitter}
utterances_tot %>%
  ggplot(aes(background, utterances, colour = background)) +
  geom_jitter(width = 0.2) +
  stat_summary(fun.y = median, geom = "point", shape = 18, size = 6, color = "black")
```

## Utterances and points

```{r}
utter_point %>%
  ggplot(aes(utterances, point)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
utter_point %>%
  ggplot(aes(utterances, point, colour = as.factor(months))) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
utter_point %>%
  ggplot(aes(utterances, point, colour = as.factor(months))) +
  geom_point() +
  geom_smooth(method = "lm") +
  facet_grid(~ background)
```
