---
title: "Significance testing"
author: "Stefano Coretta"
date: "30/08/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath("../"))
library(MASS)
library(tidyverse)
theme_set(theme_minimal())
library(itsadug)
library(tidymv)
library(lmerTest)
library(effects)
library(simr)
```

```{r read-data, message=FALSE}
gestures <- read_csv("./data/gestures.csv")

gestures_tot <- gestures %>%
  group_by(dyad, background, months, gesture) %>%
  summarise(
    count = sum(count),
    ct = sum(ct)
  ) %>%
  ungroup() %>%
  mutate(
    gesture = factor(gesture, levels = c("reach", "point", "ho_gv"))
  ) %>%
  mutate_if(is.character, as.factor) %>%
  mutate(
    back_o = ordered(background, levels = c("English", "Bangladeshi", "Chinese"))
  )

contrasts(gestures_tot$back_o) <- "contr.treatment"

utterances <- read_csv("./data/utterances.csv")

# NAs not removed in sum()
utterances_tot <- utterances %>%
  group_by(dyad, background, months) %>%
  summarise(
    utterances = sum(utterances)
  ) %>%
  ungroup() %>%
  mutate_if(is.character, as.factor) %>%
  mutate(
    back_o = ordered(background, levels = c("English", "Bangladeshi", "Chinese"))
  )

contrasts(utterances_tot$back_o) <- "contr.treatment"

hg_tot <- filter(gestures_tot, gesture == "ho_gv")
reach_tot <- filter(gestures_tot, gesture == "reach")
point_tot <- filter(gestures_tot, gesture == "point")
all_tot <- gestures_tot %>%
  group_by(dyad, back_o, months) %>%
  summarise(count = sum(count), ct = sum(ct))

hg_point_lead <- gestures_tot %>%
  dplyr::select(-ct) %>%
  spread(gesture, count) %>%
  dplyr::select(-reach) %>%
  group_by(dyad) %>%
  mutate(
    lead_point = lead(point)
  ) %>%
  filter(months != 12)

reach_point_lead <- gestures_tot %>%
  dplyr::select(-ct) %>%
  spread(gesture, count) %>%
  dplyr::select(-ho_gv) %>%
  group_by(dyad) %>%
  mutate(
    lead_point = lead(point)
  ) %>%
  filter(months != 12)

reach_point_lead <- gestures_tot %>%
  dplyr::select(-ct) %>%
  spread(gesture, count) %>%
  dplyr::select(-ho_gv) %>%
  group_by(dyad) %>%
  mutate(
    lead_point = lead(point)
  ) %>%
  filter(months != 12)

ct_point_lead <- gestures_tot %>%
  filter(gesture == "point") %>%
  dplyr::select(-gesture) %>%
  rename(point = count) %>%
  group_by(dyad) %>%
  mutate(
    lead_point = lead(point)
  ) %>%
  filter(months != 12)

utter_point_lead <- gestures_tot %>%
  filter(gesture == "point") %>%
  right_join(y = utterances_tot) %>%
  group_by(dyad) %>%
  mutate(
    lead_point = lead(count)
  ) %>%
  filter(months != 12)
```

# HGs development

```{r hg-gam}
hg_nb <- glm.nb(count ~ months, data = hg_tot)

hg_gam <- gam(
  count ~
    back_o +
    s(months, k = 3) +
    s(months, k = 3, by = back_o) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = hg_tot,
  method = "ML",
  family = negbin(0.6434)
)
summary(hg_gam)

hg_gam_null <- gam(
  count ~
    # back_o +
    s(months, k = 3) +
    # s(months, k = 3, by = back_o) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = hg_tot,
  method = "ML",
  family = negbin(0.6434)
)

compareML(hg_gam_null, hg_gam)

hg_gam_2 <- gam(
  count ~
    s(months, k = 3) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = hg_tot,
  method = "ML",
  family = negbin(0.1946)
)
hg_gam_2_null <- gam(
  count ~
    # s(months, k = 3) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = hg_tot,
  method = "ML",
  family = negbin(0.1946)
)
compareML(hg_gam_2_null, hg_gam_2)
```

```{r hg-gam-plot}
plot_smooths(hg_gam, months, facet_terms = back_o, series_length = 25)
```

# Reach development

```{r reach-gam}
reach_nb <- glm.nb(count ~ months, data = reach_tot)

reach_gam <- gam(
  count ~
    back_o +
    s(months, k = 3) +
    s(months, k = 3, by = back_o) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = reach_tot,
  method = "ML",
  family = negbin(0.986)
)
summary(reach_gam)

reach_gam_null <- gam(
  count ~
    # back_o +
    s(months, k = 3) +
    # s(months, k = 3, by = back_o) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = reach_tot,
  method = "ML",
  family = negbin(0.986)
)

compareML(reach_gam_null, reach_gam)

reach_gam_2 <- gam(
  count ~
    s(months, k = 3) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = reach_tot,
  method = "ML",
  family = negbin(0.1946)
)
reach_gam_2_null <- gam(
  count ~
    # s(months, k = 3) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = reach_tot,
  method = "ML",
  family = negbin(0.1946)
)
compareML(reach_gam_2_null, reach_gam_2)
```

```{r reach-gam-plot}
plot_smooths(reach_gam, months, facet_terms = back_o, series_length = 25)
```

## Point development

```{r point-gam}
point_nb <- glm.nb(count ~ months, data = point_tot)

point_gam <- gam(
  count ~
    back_o +
    s(months, k = 3) +
    s(months, k = 3, by = back_o) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = point_tot,
  method = "ML",
  family = negbin(0.1946)
)
summary(point_gam)

point_gam_null <- gam(
  count ~
    # back_o +
    s(months, k = 3) +
    # s(months, k = 3, by = back_o) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = point_tot,
  method = "ML",
  family = negbin(0.1946)
)

compareML(point_gam_null, point_gam)

point_gam_2 <- gam(
  count ~
    s(months, k = 3) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = point_tot,
  method = "ML",
  family = negbin(0.1946)
)
point_gam_2_null <- gam(
  count ~
    # s(months, k = 3) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = point_tot,
  method = "ML",
  family = negbin(0.1946)
)
compareML(point_gam_2_null, point_gam_2)
```

```{r point-gam-plot}
plot_smooths(point_gam, months, facet_terms = back_o, series_length = 25)
```

# All gestures development

```{r all-gam}
all_nb <- glm.nb(count ~ months, data = all_tot)

all_gam <- gam(
  count ~
    back_o +
    s(months, k = 3) +
    s(months, k = 3, by = back_o) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = all_tot,
  method = "ML",
  family = negbin(1.164)
)
summary(all_gam)

all_gam_null <- gam(
  count ~
    # back_o +
    s(months, k = 3) +
    # s(months, k = 3, by = back_o) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = all_tot,
  method = "ML",
  family = negbin(1.164)
)

compareML(all_gam_null, all_gam)
```

```{r all-gam-plot}
plot_smooths(all_gam, months, facet_terms = back_o, series_length = 25)
```

# Maternal CT development

```{r ct-gam}
ct_gam <- gam(
  ct ~
    back_o +
    s(months, k = 3) +
    s(months, k = 3, by = back_o) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = all_tot,
  method = "ML"
)
summary(ct_gam)

ct_gam_null <- gam(
  ct ~
    # back_o +
    s(months, k = 3) +
    # s(months, k = 3, by = back_o) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = all_tot,
  method = "ML"
)

compareML(ct_gam_null, ct_gam)

ct_gam_2 <- gam(
  count ~
    s(months, k = 3) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = all_tot,
  method = "ML",
  family = negbin(0.1946)
)
ct_gam_2_null <- gam(
  count ~
    # s(months, k = 3) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = all_tot,
  method = "ML",
  family = negbin(0.1946)
)
compareML(ct_gam_2_null, ct_gam_2)
```

```{r ct-gam-plot}
plot_smooths(ct_gam, months, facet_terms = back_o, series_length = 10)
```

# Mother utterances development

```{r utter-gam}
utter_gam <- gam(
  utterances ~
    back_o +
    s(months, k = 3) +
    s(months, k = 3, by = back_o) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = utterances_tot,
  method = "ML"
)
summary(utter_gam)

utter_gam_null <- gam(
  utterances ~
    # back_o +
    s(months, k = 3) +
    # s(months, k = 3, by = back_o) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = utterances_tot,
  method = "ML"
)

compareML(utter_gam_null, utter_gam)

utter_gam_2 <- gam(
  utterances ~
    s(months, k = 3) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = utterances_tot,
  method = "ML",
  family = negbin(0.1946)
)
utter_gam_2_null <- gam(
  utterances ~
    # s(months, k = 3) +
    s(months, dyad, k = 2, bs = "fs", m = 1),
  data = utterances_tot,
  method = "ML",
  family = negbin(0.1946)
)
compareML(utter_gam_2_null, utter_gam_2)
```

```{r utter-gam-plot}
plot_smooths(utter_gam, months, facet_terms = back_o, series_length = 10)
```

# Predict pointing gestures

## Hold out and gives

```{r hg-point-lm}
hg_point_lead_nb <- glm.nb(lead_point ~ ho_gv, data = filter(hg_point_lead, ho_gv < 20))

hg_point_lm <- glmer(
  lead_point ~
    ho_gv *
    background +
    (1|dyad),
  data = filter(hg_point_lead, ho_gv < 20),
  family = negbin(0.2606)
)
summary(hg_point_lm)

hg_point_lm_null <- glmer(
  lead_point ~
    ho_gv +
    background +
    (1|dyad),
  data = filter(hg_point_lead, ho_gv < 20),
  family = negbin(0.2606)
)
anova(hg_point_lm_null, hg_point_lm)
```

```{r hg-point-check}
plot(fitted(hg_point_lm), residuals(hg_point_lm))
qqnorm(residuals(hg_point_lm))
```

```{r}
hg_eff <- as_tibble(effect("ho_gv:background", hg_point_lm, xlevels = 100))

ggplot(hg_eff, aes(ho_gv, fit)) +
  geom_ribbon(aes(ymax = upper, ymin = lower), alpha = 0.2) +
  geom_line() +
  facet_grid(~ background) +
  coord_cartesian(ylim = c(0, 100))

ggplot(hg_eff, aes(ho_gv, fit)) +
  geom_ribbon(aes(ymax = upper, ymin = lower), alpha = 0.2) +
  geom_line() +
  facet_grid(~ background) +
  coord_cartesian(ylim = c(0, 20))
```


## Reaches

```{r reach-point-lm}
reach_point_lead_nb <- glm.nb(lead_point ~ reach, data = reach_point_lead)

reach_point_lm <- glmer(
  lead_point ~
    reach *
    background +
    (1|dyad),
  data = reach_point_lead,
  family = negbin(0.2681)
)
summary(reach_point_lm)
```

```{r reach-point-check}
plot(fitted(reach_point_lm), residuals(reach_point_lm))
qqnorm(residuals(reach_point_lm))
```

```{r reach-point-plot}
plot(allEffects(reach_point_lm))
```

## Maternal CT

```{r ct-point-lm}
ct_point_lead_nb <- glm.nb(lead_point ~ ct, data = ct_point_lead)

ct_point_lm <- glmer(
  lead_point ~
    ct *
    background +
    (1|dyad),
  data = ct_point_lead,
  family = negbin(0.3247)
)
summary(ct_point_lm)
```

```{r ct-point-check}
plot(fitted(ct_point_lm), residuals(ct_point_lm))
qqnorm(residuals(ct_point_lm))
```

```{r ct-point-plot}
plot(allEffects(ct_point_lm))
```

## Maternal utterances

```{r utter-point-lm}
utter_point_lead_nb <- glm.nb(lead_point ~ utterances, data = utter_point_lead)

utter_point_lm <- glmer(
  lead_point ~
    scale(utterances) *
    background +
    (1|dyad),
  data = utter_point_lead,
  family = negbin(0.2554)
)
summary(utter_point_lm)
```

```{r ct-point-check}
plot(fitted(utter_point_lm), residuals(utter_point_lm))
qqnorm(residuals(utter_point_lm))
```

```{r ct-point-plot}
plot(allEffects(utter_point_lm))
```

# Power analysis

```{r hgpl-power}
hgpl <- filter(hg_point_lead, ho_gv < 20) %>% na.omit()

pow_lm <- glmer(
  lead_point ~
    ho_gv *
    background +
    (1|dyad),
  data = hgpl,
  family = negbin(0.2606)
)
fixef(pow_lm)["ho_gv:backgroundChinese"] <- 0.3

powerSim(pow_lm, test = fixed("ho_gv:backgroundChinese", method = "z"), nsim = 1000)
```

